spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/movie-api
    username: postgres
    password: 4964
    hikari:
      auto-commit: false
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true



