package com.stepaniuk.movieapi.entitys;

public enum Genre {
    COMEDY,FANTASY,HORRORS,
    ACTION_FILM,MELODRAMA,ADVENTURES,
    MYSTICISM,DETECTIVE,ANIMATION,
    HISTORICAL,REAL_EVENTS,DRAMA,
    THRILLER,FAMILY,CRIME,
    BIOGRAPHICAL,DOCUMENTARY,SPORT,
    ROMANCE
}
